--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-03-24 12:59:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16707)
-- Name: authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authors (
    id integer NOT NULL,
    name character varying(255),
    version integer
);
ALTER TABLE ONLY public.authors ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.authors ALTER COLUMN version SET STATISTICS 0;


--
-- TOC entry 218 (class 1259 OID 16706)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.authors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 218
-- Name: authors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.authors_id_seq OWNED BY public.authors.id;


--
-- TOC entry 221 (class 1259 OID 16714)
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    isbn character varying(255) NOT NULL,
    title character varying(128),
    price numeric(12,2),
    version integer
);
ALTER TABLE ONLY public.books ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN title SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN price SET STATISTICS 0;
ALTER TABLE ONLY public.books ALTER COLUMN version SET STATISTICS 0;


--
-- TOC entry 220 (class 1259 OID 16711)
-- Name: books_authors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books_authors (
    books_isbn character varying(255) NOT NULL,
    authors_id integer NOT NULL
);
ALTER TABLE ONLY public.books_authors ALTER COLUMN books_isbn SET STATISTICS 0;
ALTER TABLE ONLY public.books_authors ALTER COLUMN authors_id SET STATISTICS 0;


--
-- TOC entry 224 (class 1259 OID 16721)
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    name character varying(64),
    email character varying(64),
    version integer
);
ALTER TABLE ONLY public.customers ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN name SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN email SET STATISTICS 0;
ALTER TABLE ONLY public.customers ALTER COLUMN version SET STATISTICS 0;


--
-- TOC entry 223 (class 1259 OID 16720)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16700)
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_rank SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN version SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN description SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN type SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN script SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN checksum SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_by SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_on SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN execution_time SET STATISTICS 0;
ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN success SET STATISTICS 0;


--
-- TOC entry 222 (class 1259 OID 16717)
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    isbn character varying(255) NOT NULL,
    sold integer,
    supplied integer
);
ALTER TABLE ONLY public.inventory ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN sold SET STATISTICS 0;
ALTER TABLE ONLY public.inventory ALTER COLUMN supplied SET STATISTICS 0;


--
-- TOC entry 226 (class 1259 OID 16725)
-- Name: line_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.line_items (
    id integer NOT NULL,
    order_id integer,
    quantity integer,
    isbn character varying(64)
);
ALTER TABLE ONLY public.line_items ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN order_id SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN quantity SET STATISTICS 0;
ALTER TABLE ONLY public.line_items ALTER COLUMN isbn SET STATISTICS 0;


--
-- TOC entry 225 (class 1259 OID 16724)
-- Name: line_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.line_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.line_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16729)
-- Name: purchase_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_orders (
    id integer NOT NULL,
    customer_id integer,
    total integer,
    status smallint,
    placed_on timestamp without time zone,
    delivered_on timestamp without time zone
);
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN customer_id SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN total SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN status SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN placed_on SET STATISTICS 0;
ALTER TABLE ONLY public.purchase_orders ALTER COLUMN delivered_on SET STATISTICS 0;


--
-- TOC entry 227 (class 1259 OID 16728)
-- Name: purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4774 (class 2604 OID 16710)
-- Name: authors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authors ALTER COLUMN id SET DEFAULT nextval('public.authors_id_seq'::regclass);


--
-- TOC entry 4779 (class 2606 OID 16736)
-- Name: authors author_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT author_pkey PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 16734)
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- TOC entry 4783 (class 2606 OID 16745)
-- Name: books pk_books; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT pk_books PRIMARY KEY (isbn);


--
-- TOC entry 4781 (class 2606 OID 16738)
-- Name: books_authors pk_books_authors; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT pk_books_authors PRIMARY KEY (books_isbn, authors_id);


--
-- TOC entry 4787 (class 2606 OID 16759)
-- Name: customers pk_customers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT pk_customers PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 16747)
-- Name: inventory pk_inventory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT pk_inventory PRIMARY KEY (isbn);


--
-- TOC entry 4789 (class 2606 OID 16761)
-- Name: line_items pk_line_items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT pk_line_items PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 16763)
-- Name: purchase_orders pk_purchase_orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT pk_purchase_orders PRIMARY KEY (id);


--
-- TOC entry 4777 (class 1259 OID 16732)
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- TOC entry 4792 (class 2606 OID 16739)
-- Name: books_authors fk_books_authors_on_authors; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_authors FOREIGN KEY (authors_id) REFERENCES public.authors(id);


--
-- TOC entry 4793 (class 2606 OID 16753)
-- Name: books_authors fk_books_authors_on_books; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books_authors
    ADD CONSTRAINT fk_books_authors_on_books FOREIGN KEY (books_isbn) REFERENCES public.books(isbn);


--
-- TOC entry 4794 (class 2606 OID 16748)
-- Name: inventory fk_inventory_on_isbn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_inventory_on_isbn FOREIGN KEY (isbn) REFERENCES public.books(isbn);


--
-- TOC entry 4795 (class 2606 OID 16769)
-- Name: line_items fk_line_items_on_book; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_book FOREIGN KEY (isbn) REFERENCES public.books(isbn);


--
-- TOC entry 4796 (class 2606 OID 16764)
-- Name: line_items fk_line_items_on_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.line_items
    ADD CONSTRAINT fk_line_items_on_order FOREIGN KEY (order_id) REFERENCES public.purchase_orders(id);


--
-- TOC entry 4797 (class 2606 OID 16774)
-- Name: purchase_orders fk_purchase_orders_on_customer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fk_purchase_orders_on_customer FOREIGN KEY (customer_id) REFERENCES public.customers(id);


-- Completed on 2026-03-24 12:59:34

--
-- PostgreSQL database dump complete
--

