spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_de_tu_db
spring.datasource.username=tu_usuario_aqui
spring.datasource.password=tu_password_aqui
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework=DEBUG
logging.level.org.springframework.jdbc=TRACE
